FROM golang:1.15-alpine AS builder
WORKDIR /build
COPY go.mod .
RUN go mod download
RUN go mod verify
COPY . .
RUN go build -o main

FROM alpine:3.11.3
WORKDIR /app
COPY static static
COPY templates templates
COPY --from=builder /build/main .
EXPOSE 80
CMD ["/app/main"]
